package com.trippack.packing;

import com.trippack.trip.Trip;

import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.Id;
import jakarta.persistence.ManyToOne;

/**
 * One line of a packing list. Items are either generated by the rules or
 * added by the user (custom). Regenerating the list only replaces generated items.
 */
@Entity
public class PackingItem {

    @Id
    @GeneratedValue
    private Long id;

    @ManyToOne(optional = false)
    private Trip trip;

    private String name;

    @Enumerated(EnumType.STRING)
    private Category category;

    private int quantity;

    /** Why the item is on the list, for example "Rain likely on Tue 14 Oct". */
    private String reason;

    private boolean packed;
    private boolean custom;

    protected PackingItem() {
        // for JPA
    }

    public PackingItem(Trip trip, String name, Category category, int quantity, String reason, boolean custom) {
        this.trip = trip;
        this.name = name;
        this.category = category;
        this.quantity = quantity;
        this.reason = reason;
        this.custom = custom;
    }

    public Long getId() { return id; }
    public Trip getTrip() { return trip; }
    public String getName() { return name; }
    public Category getCategory() { return category; }
    public int getQuantity() { return quantity; }
    public String getReason() { return reason; }
    public boolean isPacked() { return packed; }
    public boolean isCustom() { return custom; }

    public void setQuantity(int quantity) { this.quantity = quantity; }
    public void setPacked(boolean packed) { this.packed = packed; }
}
